# Generated by Django 5.1.5 on 2025-01-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackUsage',
            fields=[
                ('usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_number', models.CharField(max_length=20)),
                ('route_short_name', models.CharField(max_length=20)),
                ('departure_time', models.DateTimeField()),
                ('track', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'track_usage',
                'ordering': ['-departure_time'],
                'unique_together': {('train_number', 'departure_time')},
            },
        ),
    ]
